swagger: '2.0'
info:
  title: 'API-Enem'
  version: '1.0.0'
paths:
  /v1/exams:
    get:
      summary: "Retrieve a list of exams"
      description: "Returns a list of exams with pagination"
      parameters:
        - name: page[number]
          in: query
          type: integer
          description: "Page number for pagination"
        - name: page[size]
          in: query
          type: integer
          description: "Page size for pagination"
      responses:
        200:
          description: "A list of exams"
          schema:
            type: array
            items:
              $ref: '#/definitions/Exam'
  /v1/exams/{year}:
    get:
      summary: "Retrieve an exam by year"
      description: "Returns a single exam by year"
      parameters:
        - name: year
          in: path
          required: true
          type: integer
          description: "Year of the exam"
      responses:
        200:
          description: "An exam"
          schema:
            $ref: '#/definitions/Exam'
        404:
          description: "Exam not found"
  /v1/questions:
    get:
      summary: "Retrieve a list of questions"
      description: "Returns a list of questions with pagination"
      parameters:
        - name: page[number]
          in: query
          type: integer
          description: "Page number for pagination"
        - name: page[size]
          in: query
          type: integer
          description: "Page size for pagination"
      responses:
        200:
          description: "A list of questions"
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
  /v1/questions/{id}:
    get:
      summary: "Retrieve a question by ID"
      description: "Returns a single question by ID"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: "ID of the question"
      responses:
        200:
          description: "A question"
          schema:
            $ref: '#/definitions/Question'
        404:
          description: "Question not found"
definitions:
  Exam:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      year:
        type: integer
      disciplines:
        type: array
        items:
          type: string
      languages:
        type: array
        items:
          type: string
    
  Question:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      index:
        type: integer
      year:
        type: integer
      language:
        type: string
      discipline:
        type: string
      context:
        type: string
      files:
        type: array
        items:
          type: string
      correct_alternative:
        type: string
      alternatives_introduction:
        type: string
      alternatives:
        type: array
        items:
          type: object
          properties:
            letter:
              type: string
            text:
              type: string
            file:
              type: string
            is_correct:
              type: boolean
      exam_id:
        type: integer